# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bd04785598160185f3b5d64532b818e"
name = "omni-communication"
handle = "omni-communication"
application_url = "https://cadillac-foo-welfare-since.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://cadillac-foo-welfare-since.trycloudflare.com/auth/callback",
  "https://cadillac-foo-welfare-since.trycloudflare.com/auth/shopify/callback",
  "https://cadillac-foo-welfare-since.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
