# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bd04785598160185f3b5d64532b818e"
name = "omni-communication"
handle = "omni-communication"
application_url = "https://omni-communication-production.up.railway.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://omni-communication-production.up.railway.app/auth/callback",
  "https://omni-communication-production.up.railway.app/auth/shopify/callback",
  "https://omni-communication-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
